name: firestore_payments_api
description: My new Firestore package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  cloud_firestore: ^4.0.3
  fake_cloud_firestore: ^2.0.1
  json_annotation: ^4.4.0
  meta: ^1.3.0
  uuid: ^3.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
