name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: ../cache
  equatable: ^2.0.0
  firebase_auth: ^4.1.0
  firebase_core: ^2.4.1
  google_sign_in: ^5.2.3
  meta: ^1.3.0
  very_good_analysis: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
